version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.4.9
      - image: cimg/mysql:8.0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: |
            cd src
            composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: Setup Test Environment
          command: cp src/.env.testing src/.env
      - run:
          name: Run PHPUnit
          command: src/vendor/bin/phpunit src/tests/Feature

