version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.9
      - image: circleci/mysql:8.0.26
    environment:
      - DB_CONNECTION:  circle_testing
    working_directory: ~/ci-demo
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: |
            cd src
            composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: Run PHPUnit
          command: src/vendor/bin/phpunit src/tests/Feature


